### ISSUE TITLE
Spanish translation?

### ISSUE THREAD

**Issue by rogorido** [Fr4gorSoftware/SecScanQR#100]
Hi!

thanks for the wonderful app. As far as I see there should be a Spanish translation but in https://github.com/Fr4gorSoftware/SecScanQR/tree/master/app/src/main/res I don't see any values-es... Is maybe the pull request which is not integrated?

Otherwise I could contribute with the translation.

**Comment by Fr4gorSoftware** [comment]
Hi,
you are right we have a translation for basque but not for spanish. It would be great if you could provide a spanish translation for this project.

**Comment by rogorido** [comment]
Ok!

**Comment by Fr4gorSoftware** [comment]
Take a look at #105 maybe you give better feedback to the translation itself

**Comment by rogorido** [comment]
Ok! Soon in the next weeks...

**Comment by Fr4gorSoftware** [comment]
#105
