### ISSUE TITLE
Generates QR-Code is not stored

### ISSUE THREAD

**Issue by maddin5736** [Fr4gorSoftware/SecScanQR#101]
Hi,

I just found your app Minutes ago and I'm happy about this fact!

Your Software: 1.2.3 (16)
My device: android is 5.1.1 Huawei y6 2016

After generating a new QR-code(text, VCard or...) it is generated, but after clicking the save button "Speichern" screen return to the previous and the folder SecScanQR stays empty!

Any idea for me?

Thx for your Help!

Martin

**Comment by Fr4gorSoftware** [comment]
Hi Martin,
did you checked the folder SecScanQR (internal storage) with a file explorer or with a gallery app? Sometimes the gallery app needs some time to display those but with a file explorer/manager you should be able to see the generated QR-Codes immediately.

Thore

**Comment by maddin5736** [comment]
Hi Thore, ty for response, but I used a file man ager. And save button still not functionaöly




ich will eine richtige Tastatur...







On Sun, Jun 2, 2019 at 10:24 PM +0200, "Thore" <notifications@github.com> wrote:












Hi Martin,

did you checked the folder SecScanQR (internal storage) with a file explorer or with a gallery app? Sometimes the gallery app needs some time to display those but with a file explorer/manager you should be able to see the generated QR-Codes immediately.


Thore

**Comment by maddin5736** [comment]
Hi Thore, I hate to writing mails by smartephone:) I took file explorer but the save button is not functional. Martin




ich will eine richtige Tastatur...







On Sun, Jun 2, 2019 at 10:24 PM +0200, "Thore" <notifications@github.com> wrote:












Hi Martin,

did you checked the folder SecScanQR (internal storage) with a file explorer or with a gallery app? Sometimes the gallery app needs some time to display those but with a file explorer/manager you should be able to see the generated QR-Codes immediately.


Thore

**Comment by Fr4gorSoftware** [comment]
Moin Martin,

ich habe gerade auf meinen Gerät noch mal die App deinstalliert und den Ordner bei mir gelöscht. Danach habe ich Version 1.2.3 installiert und einen QR Code abgespeichert. Bei mir traten dabei keine Probleme auf.

Bekommst Du bei dem betätigen von dem Speichern Button eine Meldung: Im SecScanQR Ordner gespeichert und wird Dir der QR-Code über den Speichern Button angezeigt?

**Comment by maddin5736** [comment]
Hi, also code wird mir ueber dem Speicherbutton angezeigt, wechselt nach dem Buttonbetätigen einen Screen zurück...evtk. liegt es 5.1.1?




ich will eine richtige Tastatur...







On Sun, Jun 2, 2019 at 10:38 PM +0200, "Thore" <notifications@github.com> wrote:












Moin Martin,



ich habe gerade auf meinen Gerät noch mal die App deinstalliert und den Ordner bei mir gelöscht. Danach habe ich Version 1.2.3 installiert und einen QR Code abgespeichert. Bei mir traten dabei keine Probleme auf.



Bekommst Du bei dem betätigen von dem Speichern Button eine Meldung: Im SecScanQR Ordner gespeichert und wird Dir der QR-Code über den Speichern Button angezeigt?

**Comment by maddin5736** [comment]
Hi thore,

ich habe gesehen, dass ich keine Datei mit Doppelpunkten im Namen speichern kann und habe das hier gefunden:

android.text.format.DateFormat.format("yyyy-MM-dd_hh:mm:ss", now);

Könnte das ein Grund sein...Achtung gefährliches Halbwissen am Start!

Schöne Grüße 
Martin

**Comment by Fr4gorSoftware** [comment]
Moin Martin,
erst mal sorry für die späte Antwort.
Probiere mal [diese](https://github.com/Fr4gorSoftware/SecScanQR/blob/testig-new-save-mode/app-debug.apk) Version von der App. Sollte mit dieser Version alles funktionieren, liegt es wohl wirklich daran, dass dein Smartphone keine Dateien mit Doppelpunkt speichern kann (Warum auch immer :D)

MfG Thore

**Comment by webcapcha** [comment]
I just installed the app via apk file. Can't understand how feature generate qr code works (don't see appropriate item in menu)

I can only scan qr code

**Comment by maddin5736** [comment]
Moin Thore,




Kein Stress, aber die Installation endet mit “nicht installiert...“




Muss ich erst deinstallieren?




Martin




ich will eine richtige Tastatur...







On Sat, Jun 15, 2019 at 10:32 PM +0200, "Thore" <notifications@github.com> wrote:












Moin Martin,


erst mal sorry für die späte Antwort.


Probiere mal diese Version von der App. Sollte mit dieser Version alles funktionieren, liegt es wohl wirklich daran, dass dein Smartphone keine Dateien mit Doppelpunkt speichern kann (Warum auch immer :D)



MfG Thore

**Comment by maddin5736** [comment]
Hi,


on the bottom right, there is a button "generate"? - or not?




Martin




ich will eine richtige Tastatur...







On Sun, Jun 16, 2019 at 6:24 AM +0200, "webcapcha" <notifications@github.com> wrote:












I just installed the app via apk file. Can't understand how feature generate qr code works (don't see appropriate item in menu)


I can only scan qr code

**Comment by webcapcha** [comment]
No I don't see those button. Here is my main screen
https://imgur.com/MIrrrD9

**Comment by Fr4gorSoftware** [comment]
This does not look like Secscanqr at all. You should only install SecScanQR from the F-Droid store

**Comment by Fr4gorSoftware** [comment]
Moin Martin, genau die Version von F-Droid muss vorher deinstalliert werden

**Comment by maddin5736** [comment]
Hi Thore, besser!


Aber ich denke, dass ich nicht der einzige sein sollte, zumindest habe ich so gelesen...! Würde mich freuen, wenn ich in Zukunft wieder von F-droid installieren könnte-ansonsten Top Arbeit! Danke Dir!




Martin




ich will eine richtige Tastatur...







On Mon, Jun 17, 2019 at 8:30 AM +0200, "Thore" <notifications@github.com> wrote:












Moin Martin, genau die Version von F-Droid muss vorher deinstalliert werden

**Comment by webcapcha** [comment]
> This does not look like Secscanqr at all. You should only install SecScanQR from the F-Droid store

I do. But i used apk file from f-droid. Is it different? If yes, looks like a bug for me.

**Comment by Fr4gorSoftware** [comment]
Moin Martin, ja die Änderung kommt in die nächste Version, dann kannst Du sie wieder ganz normal aus dem Fdroid store laden

**Comment by Fr4gorSoftware** [comment]
@webcapcha Please refresh your packages in the F-Droid store. It seems like Fdroid installed a different app :grinning:

**Comment by webcapcha** [comment]
yeah, no it's correct. Thanks. But why that wrong application had the same name "SecScanQR"?

**Comment by Fr4gorSoftware** [comment]
@webcapcha Can you provide a link or was it in the Fdroid app?

**Comment by webcapcha** [comment]
Sure. On Friday or Saturday I went to the SecScanQR on the f-droid page and click "Download apk" link which is went to https://f-droid.org/repo/de.t_dankworth.secscanqr_16.apk

But looks like it was wrong link because (i compared the logo of application) by fact it downloaded https://f-droid.org/en/packages/com.secuso.privacyFriendlyCodeScanner/ this application.

Then I started communicate with you here. And today using the same link https://f-droid.org/repo/de.t_dankworth.secscanqr_16.apk it downloads correct application.

I'm not sure do f-droid has any logs. But the fact is fact.
