### ISSUE TITLE
Implementing WiFi connect

### ISSUE THREAD

**Issue by neremin** [Fr4gorSoftware/SecScanQR#103]
It would be great to add WiFi connection with single click, as it was already requested befor in issue #62 (https://github.com/Fr4gorSoftware/SecScanQR/issues/62#issuecomment-448216166_), but was rejected by reason of extra permissions required. In fact it does NOT, as you can see in zxing scanner - it does this without requesting permissions from the user. You can see implementation details here: [https://github.com/zxing/zxing/blob/0b9b39a74fb3d7b010fb2979c14666258d255789/android/src/com/google/zxing/client/android/wifi/WifiConfigManager.java](url)

**Comment by m-p-3** [comment]
Would also be great to have the ability to generate a QR code to connect to a network as well. I use the Zxing Generator website, but something I could run locally would be better/safer.

**Comment by Fr4gorSoftware** [comment]
I will take a look at this

**Comment by Fr4gorSoftware** [comment]
To add a network in android I have to call following function: 
And this function needs following permission: android.permission.CHANGE_WIFI_STATE
For the user it will be probably listed as permission: Need access to network
This is also the same way how zxing implemented it and they also ask for this permission. You can see this in the following [file](https://github.com/zxing/zxing/blob/0b9b39a74fb3d7b010fb2979c14666258d255789/android/AndroidManifest.xml).

If you have any other ideas to implement this without permission please let me know until then this feature is rejected

**Comment by breversa** [comment]
@Fr4gorSoftware : is that a bad thing to ask for such a permission ? Or are you simply concerned about what the (un)suspecting user may think ?

**Comment by Fr4gorSoftware** [comment]
@breversa The problem with this specific permission is that it is not visible for the user during installation and is also not a permission which will be asked at run time if the user is ok with that. If I implement this permission into the app, it will have it after installation without letting the user know and can not be disabled.

**Comment by munchkinguy** [comment]
Is there a way in which the software could interpret the QR code and display the information in a way that would make it easier for manual entry?
