### ISSUE TITLE
Share contacts via this app

### ISSUE THREAD

**Issue by ikarus23** [Fr4gorSoftware/SecScanQR#114]
I would love to share contacts via QR codes. I don't think you need an extra permission as long as the workflow is: open contacts app, select contact, use share button, select this lovely app and it will create a vcard QR code.

Thanks again for all your work. I hope your thesis went well ;)

**Comment by Fr4gorSoftware** [comment]
feature is implemented and will be part of the next release.

PS: The thesis went well ;-)

**Comment by ikarus23** [comment]
Tested on my Nexus 5X, Android 8.1. Works great! Thank you so much! Now I can use one good QR app instead of three, which are all doing just some things right.
