### ISSUE TITLE
Saved scans can not be deleted if they contain special characters

### ISSUE THREAD

**Issue by janitress** [Fr4gorSoftware/SecScanQR#119]
First of all, I love this app. I'm using it nearly every day. Thanks a thousand for your effort!

_My System Spex:_
SecScanQR Version: 1.2.4 (Build 17)
Android: 7.1.2
OS: LineageOS 14.1

**Issue:**
Saved scans can not be deleted if they contain special characters. It is possible to delete the whole list of your currents scans but you cannot delete selected scans if they contain special characters like for e.g. an apostrophe (U+0027) > **'** <.

The error message reads:

> Dieses Format wird für die Verlaufsfunktion nicht unterstützt

**Comment by Fr4gorSoftware** [comment]
Solution is implemented and will be part of version 1.2.5.

Then you will be able to open scans in the history with an apostrophe :-)
