### ISSUE TITLE
Wifi QR generator

### ISSUE THREAD

**Issue by aha999** [Fr4gorSoftware/SecScanQR#125]
Under the Generator menu, you could add a Wifi QR code generator, that enables you to make a QR code, which the clients can scan to automatically connect to the wifi.

Website that uses that feature, its code is on github: https://qifi.org/

Also, says on the website:
> Just pipe the string WIFI:S:<SSID>;T:<WPA|WEP|>;P:<password>;; through the QR code generator of your choice after reading the documentation. 

The options could be:
- Enter wifi ssid, password manually
- Create a known network QR code (where you select a known network's ssid, but you enter password manually)

If the permissions are a problem, you can just make the manual mode, or ask for permission to view the networks, when you use the known wifi feature, to copy ssid.

**Comment by glowinthedark** [comment]
Some android flavours such as MIUI have this feature OOTB. And the generated QR codes are supported by iOS via the native camera app (you get a _Join network_ prompt).

**Comment by Fr4gorSoftware** [comment]
scheduled for next release, well at least the functionality the generate WIFI QR-Codes ;-)

**Comment by Fr4gorSoftware** [comment]
is implemented and will be part of the next release :-)

**Comment by raboof** [comment]
I somehow missed this happened and randomly found the feature in the app - super cool!
