### ISSUE TITLE
Generator menu style

### ISSUE THREAD

**Issue by aha999** [Fr4gorSoftware/SecScanQR#126]
Instead of the list type of Generator menu:
- Rounded square buttons (card style) that are centered in the middle of the screen
- Every option could have a simple icon before the text, like Geo having a location pin etc.
-every option can have a different gentle colored button background

**Comment by Fr4gorSoftware** [comment]
good idea, i don't know if I put this into the next release but it will come :-)

**Comment by Fr4gorSoftware** [comment]
implemented in current dev version. Will be available with Version 1.2.7
