### ISSUE TITLE
Gradle Bug F-Droid

### ISSUE THREAD

**Issue by Fr4gorSoftware** [Fr4gorSoftware/SecScanQR#13]
Used : com.android.tools.build:gradle:3.0.1
Allowed: 4.4.1 4.4 4.3.1 4.3 4.2.1 4.2 4.1 4.0.2 4.0.1 4.0 3.5.1 3.5 3.4.1 3.4 3.3 3.2.1 3.2 3.1 3.0 2.14.1 2.14 2.13 2.12 2.11 2.10 2.9 2.8 2.7 2.6 2.5 2.4 2.3 2.2.1 2.2 2.1 1.12 1.11 1.10 1.9 1.8 1.7 1.6 1.4

**Comment by relan** [comment]
Hi,

F-Droid maintaner here. We have three issues building your app:

1. Bad Gradle distribution URL. Android Gradle plugin 3.0.1 requires Gradle 4.1 or later, while 3.3 is [specified here](https://github.com/Fr4gorSoftware/SecScanQR/blob/1.1.3/gradle/wrapper/gradle-wrapper.properties#L6). Fix: update Gradle wrapper to at least 4.1.
2. Android Gradle plugin 3.0.1 is available only in Google Maven repo. Fix: add `google()` into your [top-level build.gradle](https://developer.android.com/studio/build/index.html#top-level).
3. Lint warnings are fatal. Fix: make them non-fatal:

```
android {
    lintOptions {
        abortOnError false
    }
}
```

Steps to reproduce those issues:

    cd app
    gradle assembleRelease

**Comment by Fr4gorSoftware** [comment]
Hi relan,
I did the things you mentioned. Project should now build properly for F-Droid

**Comment by relan** [comment]
Great, looking forward to a new Git tag.
