### ISSUE TITLE
Error when scanning

### ISSUE THREAD

**Issue by OmlineEditor** [Fr4gorSoftware/SecScanQR#131]
does not scan this type of image. closes with an error.
this type of image can often be seen on Chinese products
bring the scanner to the screen and check for yourself.
![bug](https://user-images.githubusercontent.com/13348933/72747715-77576100-3bc6-11ea-9326-a6e53a2f95ca.jpg)

**Comment by user8446** [comment]
I received a toast msg of "no valid input for this format". It's clearly not a standard QR code format.

**Comment by OmlineEditor** [comment]
well, it's not QR. At least make sure that the app doesn't close with an error. I have it closed with an error and I am thrown to the main desktop.

**Comment by jo-so** [comment]
I'm having the same problem with this Data Matrix on a Samsung mobil phone battery.

![Samsung mobil phone battery](https://user-images.githubusercontent.com/23032146/74335688-065a3200-4d9d-11ea-9981-9ccaf9657b55.jpg)

Even if SecScanQR can't interpret the content, it would be helpful to show the bytes like Binary Eyes does.

![Binary Eyes](https://user-images.githubusercontent.com/23032146/74358576-f9036e80-4dc1-11ea-8f46-693d428d1e28.png)

**Comment by Fr4gorSoftware** [comment]
First of all sorry for the late answer.
@OmlineEditor I tried it also on my side and it does not seem to be an code format that is supported by ZXing library. The app should not crash with Version 1.2.6 anymore which is currently in development.

@jo-so In your case it does not work because the colors are inverted from the standard color scheme. At the moment there is no solution in SecScanQR to scan inverted codes. I don't see the benefit it to show information on bytes level.

**Comment by jo-so** [comment]
SecScanQR can scan the code on the battery, but it dies with »Keine gültige Eingabe für dieses Format« (invalid input for this format).

**Comment by OmlineEditor** [comment]
fix application crash error. and you message that this is not a supported format if the application does not know how to scan it. The application should not crash.

**Comment by Fr4gorSoftware** [comment]
As I said the problem does not show up anymore in the current dev version 1.2.6

**Comment by OmlineEditor** [comment]
OK. Thank you for developing the program. I'm waiting for an update.
I am very happy to use your program. You have a good program please continue to develop the project
