### ISSUE TITLE
[BUG] QR codes to a URL file download fails

### ISSUE THREAD

**Issue by user8446** [Fr4gorSoftware/SecScanQR#132]
If a QR code is scanned that is a URL to a file download and then "Open in Web" is clicked in SecScanQR, Chrome will open the last tab used but is not directed to the URL. You have to "copy" and then "paste" into chrome for it to work.
However, after downloading via the copy/paste URL if you repeat the above steps then it works as expected and you receive a notification from chrome if you want to download the file again.

**Comment by Fr4gorSoftware** [comment]
Can you give me more details about it. I tried to replicate this issue on my side but did not faced any issues.

- Device
- Android Version
- Browser
- Link where you faced this problem

**Comment by user8446** [comment]
Sure...

Moto 5G Plus
Android 8.1
Chrome
https://www.waveapps.com/receipts - scroll down and you'll see the QR download for Android

**Comment by Fr4gorSoftware** [comment]
I tested it now on my two devices and it worked just fine.
Samsung galaxy S7 with Android 8
Xiaomi Mi 9T Pro with Android 10

Maybe try resetting your settings regarding the browser or try other browsers. If nothing works it is probably a device specific problem...
