### ISSUE TITLE
vCard add new fields

### ISSUE THREAD

**Issue by OmlineEditor** [Fr4gorSoftware/SecScanQR#133]
When creating a user card, these fields are not present, please add them.
https://en.wikipedia.org/wiki/VCard

- BDAY
- NOTE
- PHOTO (use url)

**Comment by Fr4gorSoftware** [comment]
I will take a look at this. If the android contact app can handle this information I will give you feedback and will implement it :-)

**Comment by OmlineEditor** [comment]
fix application crash error. and you message that this is not a supported format if the application does not know how to scan it. The application should not crash.

**Comment by OmlineEditor** [comment]
> f the android contact app can handle this information

This is the official standard that has been supported since the old Android version 2

**Comment by Fr4gorSoftware** [comment]
Implemented in current dev version. Will be available with version 1.2.7
