### ISSUE TITLE
Suggestion: Use v1.2.4 style items in generate/history

### ISSUE THREAD

**Issue by floppyD** [Fr4gorSoftware/SecScanQR#134]
I know it's just my opinion but I really think that the UI used to look better overall in the previous versions, the items inside the submenus used to look like actual material design items, not this weird thing that come from top to bottom with fading dividers. So I hope you reconsider this change, really I wouldn't be bothering you if I didn't think it looked nice before.

**Comment by Fr4gorSoftware** [comment]
i can understand your point. The reason why I did this is to support the dark mode even in the ListView. I can try to deactivate the animation (which had the purpose to load data dynamically) so it should look like the normal ListView

**Comment by Fr4gorSoftware** [comment]
Implemented in dev version and will be part of version 1.2.6
