### ISSUE TITLE
Text placement is wrong

### ISSUE THREAD

**Issue by floppyD** [Fr4gorSoftware/SecScanQR#135]
That's how it looks when I scan a QR after updating to 1.2.5 (sorry for the quality, but screenshots don't work anymore)
![new](https://user-images.githubusercontent.com/29208110/74126642-38aa3a80-4bb7-11ea-8379-cadee282d199.jpg)

**Comment by Fr4gorSoftware** [comment]
Thank you for reporting. On my two test devices I did not had this issue. I will take a look at this and will implement a fix for the version 1.2.6 which is currently in development :-)

**Comment by Fr4gorSoftware** [comment]
Fixed in the current development version and will be available in version 1.2.6 for all users.

**Comment by floppyD** [comment]
It doesn't bother that much, the only real downside I see is making the recent apps screen white. Maybe implement a toggle under options? I've seen apps that went with this approach before.
