### ISSUE TITLE
Prevent duplicates in history

### ISSUE THREAD

**Issue by jo-so** [Fr4gorSoftware/SecScanQR#137]
Could you add an option to the settings menu in history to not save repeated scans, i.e. if a scan yields the same result as the previous one, don't put it into the history?

I sometime scan some codes more than once, but in the history I really need only one event. The app Barcode scanner has such a setting to opt-in for duplicates.

**Comment by Fr4gorSoftware** [comment]
Planed together with issue #138 for one of the next releases

**Comment by Fr4gorSoftware** [comment]
implemented in current development version and will be available with version 1.2.7 (#164)
