### ISSUE TITLE
Record time and code type in history

### ISSUE THREAD

**Issue by jo-so** [Fr4gorSoftware/SecScanQR#138]
It would be helpful to have the time and date of the scan and which type of code (QR code, Data matrix, Bar code) it was in the history.

**Comment by Fr4gorSoftware** [comment]
Is planed for one of the next releases :-)

**Comment by floppyD** [comment]
Showing the QR itself in the "Code information" page would be a nice touch too.

**Comment by Fr4gorSoftware** [comment]
@floppyD will be added when history will be reworked in one of the next versions

**Comment by Fr4gorSoftware** [comment]
implemented in current development version. Will be available with version 1..27
