### ISSUE TITLE
[Feature Request] read qr code from image

### ISSUE THREAD

**Issue by nottheend** [Fr4gorSoftware/SecScanQR#142]
Brilliant app :-)

I would like to ask for a feature request: read qr code from images

That would ease life a lot, whenever you have the code as image already, just share it with qr code reader

**Comment by Fr4gorSoftware** [comment]
This is already possible over the gallery app. Just share the image to the SecScanQR app and it will try to recognize the QR-Code

**Comment by nottheend** [comment]
Thanks for the comment!

I tried the recommended way, but only a beacon appears:
```
File not found
```
_localized in my language_

Do I miss anything else?

**Comment by Fr4gorSoftware** [comment]
Is it a digital copy of a qr-code? The library has problems when the qr-code was shot as a photo by the camera. 
Can you also tell me which language you are using?

**Comment by nottheend** [comment]
Thanks for the reply.

It is correct, it works with a QR code shared to the app! Just tried it again.

I was testing it with a encrypted qr code that's why it didn't work.

My local language is German.

As a minor improvement: the toast message could be change to a more speaking message like "no valid QR signature found"

**Comment by Fr4gorSoftware** [comment]
great to hear. I will change the German error to a more precise one :-)
