### ISSUE TITLE
[feature request] ISBN code from OCR

### ISSUE THREAD

**Issue by drzraf** [Fr4gorSoftware/SecScanQR#144]
Google's [mk-kit](https://developers.google.com/ml-kit) is a free & opensource wrapper (which can also be used with tflite TensorFlow models).
There is a [Text Recognition](https://firebase.google.com/docs/ml-kit/android/recognize-text) class that could be a good base for OCR.

If that sounds possible and fits project's scope, this would allow scanning ISBNs (and other) numeric codes straight from OCR what would be very useful for older books (from the post-ISBN but pre-barcode era).

**Comment by Fr4gorSoftware** [comment]
I think machine learning is out of scope for this project, sorry.
