### ISSUE TITLE
[BUG] When scanning Data Matrix code SecScanQR crashes

### ISSUE THREAD

**Issue by Saboe** [Fr4gorSoftware/SecScanQR#145]
I've tried to scan a data matrix code which contains obviously non-ASCII characters (scanned with another scanner) then SecScanQR crashes with the error message "No valid input for this format".
Used device: Fairphone 3
Example data matrix: https://www.irishapps.com/wp-content/uploads/2014/04/Other_-2_D_-Code_-Types_05.jpg

**Comment by Fr4gorSoftware** [comment]
Fix implemented in current dev version. Will be available for users with version 1.2.7
