### ISSUE TITLE
[BUG] Text overlaps

### ISSUE THREAD

**Issue by Saboe** [Fr4gorSoftware/SecScanQR#146]
When scanned a Portable Data File 417 code the text message of the identified code "PDF_417" and the text "Code information:" overlaps completely.
Used device: Fairphone 3
Used code: https://www.irishapps.com/wp-content/uploads/2014/04/Other_-2_D_-Code_-Types_04-copy.jpg
Because I can't make a screenshot of it (why?) it looks similar to this:
Code Infxxxxxxon:
The displayed image of the code (on the left to "Code format:")  is too small in height so that the text of the identified code will be placed under the text "Code information:".

**Comment by Fr4gorSoftware** [comment]
Fix implemented in current dev version. Will be available for users with version 1.2.7
