### ISSUE TITLE
Generating qr code for Arabic is not supported

### ISSUE THREAD

**Issue by AlbahrawyAlalimi** [Fr4gorSoftware/SecScanQR#147]
Does not support the creation of the qr code for the Arabic language, when creating the qr code in the Arabic language and rescanning it shows question marks where the letters are. Thanks for your effort

**Comment by Fr4gorSoftware** [comment]
Can you give me an example text to test why this happens?

**Comment by AlbahrawyAlalimi** [comment]
The problem occurs with any Arabic text, and you can try that, for example, "شركة البرنس للدعاية والاعلان"

**Comment by Fr4gorSoftware** [comment]
Thanks for the help :-)
Bug is fixed in current dev version. Will be available with version 1.2.7
