### ISSUE TITLE
[FR] "Copied to clipboard" toast position

### ISSUE THREAD

**Issue by breversa** [Fr4gorSoftware/SecScanQR#148]
Hello !

Would it be possible to move the "copied to clipboard" (see #6) somewhere else than on the bottom of the screen ?

Currently, on my devices (4,5" and 8" screens), this toast appears over, and masks the buttons at the bottom of the screen, forcing me to either :
- Wait until the toast disappears
- Tap the toast to make it disappear, then tap the button I want

Both these solutions feel unnecessary slow or tedious.

**Comment by Fr4gorSoftware** [comment]
implemented in current dev version. Will be available with version 1.2.7
