### ISSUE TITLE
Window "About"

### ISSUE THREAD

**Issue by Valdnet** [Fr4gorSoftware/SecScanQR#150]
Steps:

1. Change the Android language to Polish.
2. Launch the program.
3. Choose from the app menu: About.

In the "About" window, the descriptions leave the information window on the right.

App:
Android 10
SecScanQR 1.2.6

**Comment by Fr4gorSoftware** [comment]
On my side it looks like this:
![Bildschirmfoto vom 2020-05-02 22-17-08](https://user-images.githubusercontent.com/30445568/80891211-ef9fe900-8cc2-11ea-8f6d-24ee3610eceb.png)

Can you give me the size of your phone and which phone you are using?

**Comment by Valdnet** [comment]
Model: Huawei P Smart 2019

Display: 6,21 ", 2340 x 1080 pixels

**Comment by Fr4gorSoftware** [comment]
I think I fixed the problem in the development version. I emulated the exact sizes of your phone. If the problem still exists with version 1.2.7 please let me know

**Comment by Valdnet** [comment]
@Fr4gorSoftware In version 1.2.7 the problem persists.

**Comment by Fr4gorSoftware** [comment]
Can you deliver a screenshot, in v172 this should be possible again

**Comment by Valdnet** [comment]
This is what it looks like:
![obraz](https://user-images.githubusercontent.com/47037905/97086250-5ffc4700-1622-11eb-9dab-065da4d6639f.png)

**Comment by Fr4gorSoftware** [comment]
complete about redesign planed for version 1.2.8 #203
