### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by StevanWhite** [Fr4gorSoftware/SecScanQR#157]
I don't think your app needs the "dangerous" permissions WRITE_EXTERNAL_STORAGE or READ_EXTERNAL_STORAGE at all.  I encourage you to minimize such permissions.

The "history" function could be handled easily with a key-lookup database (maybe more easily than with files).

Instead of "saving" a generated code, let the user "copy" or "share" it -- in more Android-esque fashion.

**Comment by Fr4gorSoftware** [comment]
The history is not the reason for this permission. You need to give the app this permission only for saving generated gr-codes. I will take a look at the possibility to share the generated qr-code so the user can decide between these two methods. If the user uses a quite current Android version, the user can decide when he hits the save button, if he wants to give the app the permission or not.

**Comment by Fr4gorSoftware** [comment]
implemented in current dev version. Will be available with version 1.28
