### ISSUE TITLE
There is a copy of SecScanQR on the Play Store and it contains ads

### ISSUE THREAD

**Issue by daveloyall** [Fr4gorSoftware/SecScanQR#162]
I just thought you would like to know that this exists: https://play.google.com/store/apps/details?id=com.dankworth.secscanqr
I apologize in advance for submitting this as an "Issue"... it is more of a comment. :)

**Comment by Fr4gorSoftware** [comment]
No need to apologize. Thank you very much for reporting this app to me. I will get in contact with Google to delete this specific app / developer from the app store

**Comment by Fr4gorSoftware** [comment]
was removed by google
