### ISSUE TITLE
[FR] QR scanning from gallery photo

### ISSUE THREAD

**Issue by Dre-OS** [Fr4gorSoftware/SecScanQR#167]
What if a QR that a user took a picture from the past could be scanned by the app, it would be a great feature for people who didn't have a QR scanner in the past but want to scan the photo when they have the software to do it.

**Comment by Fr4gorSoftware** [comment]
This feature is already implemented. When you click on share in your gallery app then you can send a foto to SecScanQR to look for a QR-Code
