### ISSUE TITLE
Last scanned barcode displayed even after Reset / clear history

### ISSUE THREAD

**Issue by jtn20** [Fr4gorSoftware/SecScanQR#168]
After I have scanned a barcode, a visual representation of it is shown on the main screen, alongside UI elements "Code format: QR_CODE" "Code information: ...".

If I then press the Reset button (from the main screen), the visual representation remains on screen (now between "SecScanQR" and "Press on the Scan Button ..."). I don't see any way in the UI to get rid of it; clearing history (dustbin icon on history screen) doesn't help either. Closing the app gets rid of it.

I'd have expected the Reset button to forget this information.

**Comment by Fr4gorSoftware** [comment]
fixed in current dev version and will be available with version 1.2.7
