### ISSUE TITLE
Leave out photo when sharing a contact

### ISSUE THREAD

**Issue by joesse** [Fr4gorSoftware/SecScanQR#169]
When I try to share a contact via SecScanQR it doesn't work when there is a photo attached to the contact. I guess it's just too much data for the QR Code. So you should ignore the photo when creating the QR code.

**Comment by Fr4gorSoftware** [comment]
Could you deliver a example where you faced this problem?

**Comment by joesse** [comment]
I just created two contacts: one is a copy of the other except that I deleted the "photo".
[Bart with pic.txt](https://github.com/Fr4gorSoftware/SecScanQR/files/5440243/Bart.with.pic.txt)
[Bart Simpson.txt](https://github.com/Fr4gorSoftware/SecScanQR/files/5440245/Bart.Simpson.txt)
(in order to upload these files at github I had to rename them to *.txt. They are *.vcf files)
When I try to share the contact with picture via SecScanQR I get an error "Keine gültige Eingabe für dieses Format" - roughly: invalid entry for this format. The contact without picture can be shared without problem.
Google's standard contacts app, v. 1.4.22
Android 7.1.2

**Comment by Fr4gorSoftware** [comment]
With which generator did you created the QR-Code? Didn't found any QR-Code Generator which supports JPEG photos as part of the vcard information

**Comment by Fr4gorSoftware** [comment]
At the moment only the following properties of a scanned vcard get transfered to your contacts app: N, BDAY, ORG, URL, EMAIL, TEL (CELL, WORK, HOME, VOICE), ADR and NOTE. This means the photo property is already igonered.

**Comment by Fr4gorSoftware** [comment]
You are right, the library gives the following feedback in the background:
![grafik](https://user-images.githubusercontent.com/30445568/97234413-09893700-17e1-11eb-853b-19c4ecdefc81.png)
With the next version there will be the following message for the user: "Too much information for a QR-Code".
