### ISSUE TITLE
No ability to take screenshots of the app while in use

### ISSUE THREAD

**Issue by TheGinGear** [Fr4gorSoftware/SecScanQR#171]
Whenever you try to take a screenshot within the app anywhere outside of scanning the scan section, where the camera is actually open, gives the
"**Couldn't save screenshot**
Taking screenshots isn't allowed by the app or your organization" 
notification if you try.
Is this intentional? 
Using a pixel 3a on the latest firmware.

**Comment by Fr4gorSoftware** [comment]
Is already solved in current dev version and will be possible in version 1.27
