### ISSUE TITLE
Use a localization platform

### ISSUE THREAD

**Issue by yarons** [Fr4gorSoftware/SecScanQR#180]
There are many offerings such as Weblate (fully open source), Transifex (Closed source but housing open source for free), Crowdin (same), TranslateWiki, etc.

I'd love to help with the transition.

**Comment by Fr4gorSoftware** [comment]
I will look which solution suites the best for this project. Stay tuned

**Comment by Fr4gorSoftware** [comment]
I now tried Transifex. Can you check if everything works?
https://www.transifex.com/t-dankworth/secscanqr

**Comment by yarons** [comment]
Looks good, I've asked to establish a Hebrew team, you'll need to approve my request so I can start testing (while actually contributing).

There's a Transifex CLI tool to pull all the changes, you can do this before every new release or periodically as you please.

**Comment by Fr4gorSoftware** [comment]
I accepted your request. I will take a look at the CLI functionality

**Comment by yarons** [comment]
The first request was about creating the team, now I've requested to join the team, waiting for your second approval :) sorry about that.

**Comment by Fr4gorSoftware** [comment]
No problem, I thought I overlooked it

**Comment by yarons** [comment]
It works great from my side, since I've made some changes to Hebrew you're supposed to pull a new language with the changes I've done, if it works I'll continue translating and you'll be able to commit the translation once it's 100% complete.

BTW we may need to talk about polishing the RTL directionality of the UI:
https://engineering.atspotify.com/2019/04/15/right-to-left-the-mirror-world/

The basic principals are explained using CSS, obviously Android layout is different but you'll get the hang of it :)

Thank you!

**Comment by Fr4gorSoftware** [comment]
I checked the genearted XML file and it is in the correct format for android projects. 

Thank you for the tip with RTL. I will check how much effected the app is (Android does a lot of the stuff automatically

**Comment by Fr4gorSoftware** [comment]
Thank you for your translation. I checked with your translation RTL.

Here are the results:
<img width="399" alt="Unbenannt" src="https://user-images.githubusercontent.com/30445568/97883448-2c59a500-1d25-11eb-9ebf-147033f3fcdd.PNG"><img width="399" alt="Unbenannt2" src="https://user-images.githubusercontent.com/30445568/97883454-2cf23b80-1d25-11eb-8783-8161cbd1e6e6.PNG">
<img width="269" alt="Unbenannt3" src="https://user-images.githubusercontent.com/30445568/97883455-2d8ad200-1d25-11eb-91c7-6f952d3c66b7.PNG">

**Comment by yarons** [comment]
It looks amazing, the Wifi text on the bottom (to the right) seems misaligned, everything else looks great.
