### ISSUE TITLE
Back button not working in SecScanQR

### ISSUE THREAD

**Issue by sahmmie** [Fr4gorSoftware/SecScanQR#19]
#### Expected behavior
I launched SecscanQR, Tapped on the 3 dotted icon by the right, then selected settings, tapped scanner so i can set the scanner, then return back to the start page.

#### Actual behavior
when i clicked on settings, then selected scanner i set what i wanted to set, i pressed the back button by the top it took me back once to the page that says Scanner i tapped the back button again nothing happened i couldn't return back to the start except i quit the app.

#### How to reproduce

[download here](https://f-droid.org/packages/de.t_dankworth.secscanqr/)

Launch SecScanQR,
click the 3 dotted icon,
click settings,
Tap the back button.

Device Used: Infinix Note 3 or Infinix X601

Operating system: Android 7.0 Nougat

App Version 1.1.1 (4) - Added on 2017-11-14

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/ED7Kg8g77GI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@sahmmie/back-button-not-working-in-secscanqr">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Fr4gorSoftware** [comment]
Thank you for reporting this problem. It seems like there is a bug in the standard google settings page. The problem is that there is no working fix out there for this problem which probably forces me to rewrite the settings page.

**Comment by Fr4gorSoftware** [comment]
Update: Fix is implemented and will be available for Version 1.1.5
