### ISSUE TITLE
Messed up layout

### ISSUE THREAD

**Issue by floppyD** [Fr4gorSoftware/SecScanQR#194]
1.2.7
PT-BR language

![Screenshot_20201104-131457_SecScanQR](https://user-images.githubusercontent.com/29208110/98137395-b1b59480-1ea0-11eb-8952-6538fedf1fd0.png)

**Comment by Fr4gorSoftware** [comment]
On my side with version 1.2.7 it looks like this:
![Screenshot_20201104-205830_SecScanQR](https://user-images.githubusercontent.com/30445568/98161540-32e04c00-1ee0-11eb-85b8-5d3293594870.jpg)

Can you give me more details about your device (size, resoultion, android version and phone name) and can you send me a screenshot from the about dialog?

**Comment by floppyD** [comment]
Sure. It's a Moto G3, running Android 10. 1280x720, 411dp.
![Screenshot_20201104-193730_SecScanQR](https://user-images.githubusercontent.com/29208110/98175910-425a9780-1ed6-11eb-933f-9319d47dede0.png)

**Comment by Fr4gorSoftware** [comment]
should be fixed with version  1.2.8
