### ISSUE TITLE
Issues generating Aztec codes

### ISSUE THREAD

**Issue by nataedu** [Fr4gorSoftware/SecScanQR#197]
Hi, 

I have the version 1.2.7 (Build 20) and I am unable to generate Aztec codes. I get the following error  :
![20201202_111509](https://user-images.githubusercontent.com/35372055/100859944-c9743e80-3487-11eb-8b43-832e8eea5807.jpg)

Edit : this is for the "text" option, but I get similar errors on the others

**Comment by Fr4gorSoftware** [comment]
Fixed in current dev version. Will be available with version 1.2.8
