### ISSUE TITLE
Recognise and properly handle QR codes with wi-fi network info

### ISSUE THREAD

**Issue by munchkinguy** [Fr4gorSoftware/SecScanQR#199]
SecScanQR allows users to generate QR codes that encode Wi-Fi network info. However, when scanning a Wi-Fi QR code with SecScan, the app does not interpret such a code as an instruction to add a Wi-Fi network, and there is no button at the bottom to tell the app to add the new info to the phone's saved networks.

**Comment by Fr4gorSoftware** [comment]
Please take a look at this: https://github.com/Fr4gorSoftware/SecScanQR/issues/103#issuecomment-626052489
