### ISSUE TITLE
Feature wish: clickable link or open in browser button

### ISSUE THREAD

**Issue by frauhottelmann** [Fr4gorSoftware/SecScanQR#20]
Can you make the links clickable once scanned or add a open in browser button?
Yes I can paste the link or share it to flashify, but that would be so much quicker 😊
Thanks

**Comment by Fr4gorSoftware** [comment]
Good idea, I will implement this feature in the upcoming release

**Comment by Fr4gorSoftware** [comment]
Feature is implemented and will be available with Version 1.1.5
