### ISSUE TITLE
QR-Codes starting with "URL:"

### ISSUE THREAD

**Issue by Sogolumbo** [Fr4gorSoftware/SecScanQR#200]
I ran into QR codes which encode urls like this:
`URL:https://...`
I don't think this is normal but it would be nice if we would handle this nicely.
Currently opening this in the browser will lead to a useless google search.

### Workaround
Copy text to clipboard, paste it into the browser and edit it there (or edit it in a text editor and then copy it into the browser).

### Possible Solutions
- Detect strings starting with `URL:` and remove it from the link that's parsed to the browser
- Make the scanned text selectable. This way one could manually select the right part of the link and then press copy or share to open it in a browser.

**Comment by Fr4gorSoftware** [comment]
implemented in current dev version and will be available with the next version
