### ISSUE TITLE
Icon / logo design proposal

### ISSUE THREAD

**Issue by s-yous** [Fr4gorSoftware/SecScanQR#22]
Hi @Fr4gorSoftware  , 
I'm a graphic designer and i'm willing to design an icon and a logo for your application and i need your permission before start .

Thank you.

**Comment by Fr4gorSoftware** [comment]
Hi,
that would be great. You have my permission :-)

**Comment by s-yous** [comment]
Hi , 

My following design is not completely a new concept but is just an enhancement about the existing one , i tried to combine the QR code with the privacy shaped with a shield .
  
![idea](https://user-images.githubusercontent.com/37163527/37804451-980387f4-2e34-11e8-8c46-e25583ae6ff0.png)

I designed 3 icon types with two different colors : Blue and Red-Orange because they means the stability , confidence and trust , and that's what i got : 

![icon-variation](https://user-images.githubusercontent.com/37163527/37804439-9106f4c2-2e34-11e8-83ca-2847c5373412.png)

And this is the logotype : 

![logotype](https://user-images.githubusercontent.com/37163527/37804434-8a940490-2e34-11e8-9077-6daeddfa4b9c.png)


Let me know about the best icon in term of colors or shapes , also if you have any changes or thoughts about the design, it'll be very helpful.

Hope you like my work ! 
Thank you.

**Comment by Fr4gorSoftware** [comment]
Hi,
I really like the shape of the third picture and have an idea for the color of the lines in the corner (which should represend the scanning). Let's look how they would look like when you make them red and the "Scan" in SecScanQR.

Thank you for your effort

**Comment by s-yous** [comment]
I made two icons , one with a white background and the other with white ( i prefer the white ) 

![color-variation](https://user-images.githubusercontent.com/37163527/37840234-c96a00b0-2ebc-11e8-93e5-ae45ccbf2830.png)

and this is the icon in term of size changing : 

![size variation](https://user-images.githubusercontent.com/37163527/37840239-cdd864a2-2ebc-11e8-98fa-6c516c532154.png)

and this is the logotype : 

![logotype](https://user-images.githubusercontent.com/37163527/37840250-d50f98b2-2ebc-11e8-8aeb-a828ca23543d.png)

If you need any other changes let me know

**Comment by Fr4gorSoftware** [comment]
Hi, 
I also prefer the second one with the white background. I have an another small change idea: that the shield for privacy is in blue and the "Sec" in SecScanQR but keep the red lines and the red color of Scan in "SecScanQR"also.

Thank you for your effort

**Comment by s-yous** [comment]
![logotype2](https://user-images.githubusercontent.com/37163527/37843556-8c50e85c-2ec5-11e8-91e3-59c6c7f563eb.png)
![icon](https://user-images.githubusercontent.com/37163527/37843583-a8620b20-2ec5-11e8-806b-003a58b23dd8.png)

What do you think ? 
My opinion : i don't like the multicolor version , maybe this is better : 

![logotype3](https://user-images.githubusercontent.com/37163527/37844532-667bbfc8-2ec8-11e8-953d-031da9cd0f80.png)

**Comment by Fr4gorSoftware** [comment]
Yeah you are right. The single color version is way better. My favorite design is the one below.

![grafik](https://user-images.githubusercontent.com/30445568/37850824-eaf96372-2edc-11e8-8201-9afc80e75228.png)
This looks really nice!

Thank you for your effort

**Comment by s-yous** [comment]
Great !  
I'll generate and upload the icons and the logotype with monochrome version in vector formats ( AI / EPS / PDF / SVG ) so you can edit them later if you want and also the direct use format ( PNG ) .

**Comment by s-yous** [comment]
This is the monochrome version : 

![monochrome version](https://user-images.githubusercontent.com/37163527/37853700-1ca1fe9c-2ee8-11e8-8141-f6dbe8329147.png)

In this folder you'll find a .zip file contains all the necessary files to be used directly into you application (hpdi - mdpi - xhdpi.. ) [ ic_launcher.zip ] and the other files : [Download Here](https://drive.google.com/open?id=1UG1UOzTESAhTKKeiOC8vdQoeyDcGrLuN) .

I hope you like my design and use it the near future as well :D 
Thank you for the opportunity .

**Comment by Fr4gorSoftware** [comment]
Thank you verry much. The logo will be implemented in version 1.1.5. I will put your name and your github page in the about section of the app and on github as well ;-)
