### ISSUE TITLE
Option to disable scan history

### ISSUE THREAD

**Issue by nikwen** [Fr4gorSoftware/SecScanQR#24]
Awesome application! Thanks for that! :)

It would be nice if there was an option to disable the scan history completely, i.e. hiding the tab and not saving scanned codes anywhere.
This would allow for a maximum amount of privacy. Where no data is saved, no data can be compromised.

**Comment by Fr4gorSoftware** [comment]
Good idea! 
It will be implemented in the next version of SecScanQR

**Comment by nikwen** [comment]
That's cool! Thank you so much! :)
I'm really looking forward to receiving the update on F-Droid.
