### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by sniperle** [Fr4gorSoftware/SecScanQR#25]
Add a black theme for amoled displays please.

**Comment by Fr4gorSoftware** [comment]
If this is possible it will be added to the list of upcomming features: https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Fr4gorSoftware** [comment]
I tried to implement it, but I did not get a useful result. So for now there will be no Dark Theme

**Comment by Fr4gorSoftware** [comment]
#43 I have dealt with this topic again and achieved the first result.
