### ISSUE TITLE
Open with custom URL

### ISSUE THREAD

**Issue by sniperle** [Fr4gorSoftware/SecScanQR#26]
Add a switch or another button to open codes with a custom URL not just only google search please.

example: https://www.codecheck.info/product.search?q=%s
or: https://de.openfoodfacts.org/cgi/search.pl?search_terms=%s&search_simple=1&action=process

The above examples are from zxing barcode reader where the substitutions are:
%s = content
%f = format
%t = type

**Comment by Fr4gorSoftware** [comment]
Added to the list of upcoming features: https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Fr4gorSoftware** [comment]
Implemented in Version 1.1.7 (There will be an options menu for search engines)
