### ISSUE TITLE
More code generation schemes

### ISSUE THREAD

**Issue by DocSniper** [Fr4gorSoftware/SecScanQR#27]
Add more generation schemes e.g. for WiFi networks.
Please have a look at this: https://zxing.appspot.com/generator/

**Comment by Fr4gorSoftware** [comment]
Already on the list for upcoming features: https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Fr4gorSoftware** [comment]
added new schemes with version 1.2.6
