### ISSUE TITLE
feature request: other 2d codes  formats

### ISSUE THREAD

**Issue by lgasp** [Fr4gorSoftware/SecScanQR#3]
Hi I would like to ask, out of curiosity, what library are you using to generate/read qr codes? Can you anable other kinds of standards (like data matrix)?

**Comment by Fr4gorSoftware** [comment]
Hi,
I am using ZXing for generating QR-Codes. Other formats should be possible like data matrix. Please check the link below and take a look at the supported formats and tell me which formats were interesting for you. 
https://zxing.github.io/zxing/apidocs/com/google/zxing/BarcodeFormat.html

**Comment by lgasp** [comment]
ZXing supports a lot of formats and is pretty good, in my opinion. I used it for a project, and it is capable of autonomously identify the code format. 
If I can, I would like to suggest two possible implementations, for a multi-code reading;

1. Enable all formats and let Zxing identify which one it is.
2. Let the user choose the available formats in the preferences

Also, I think it would be useful to let the user choose the code format in the generation section

**Comment by Fr4gorSoftware** [comment]
The reading process is already implemented like it is described in suggestion no. 1.
I like the idea to let the user generate more than QR-Codes. I added it to the todo list for the upcoming releases.
https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Fr4gorSoftware** [comment]
I am currently testing the different formats from ZXing and they have a problem with some of them. Datamatrix and MAXICODE are just 2 examples because these parts are forks of other projects. I will now check every supported format and all working formats will be added to the next version.
