### ISSUE TITLE
Feature Request: Color inversion switch to scan white QR codes printed on a black background

### ISSUE THREAD

**Issue by Wolfram-Wolf** [Fr4gorSoftware/SecScanQR#30]
I've come across several QR codes (printed on the back of small devices, like wireless mice) which are printed in white on black. To be able to scam these codes, a colour inversion switch could come in handy (the sort of colour inversion implemented in the Android Accessibility settings).

**Comment by Fr4gorSoftware** [comment]
If this is possible it will be added to the list of upcoming features: https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Fr4gorSoftware** [comment]
Is implemented in current dev version and will be available with version 1.2.8.
Scanner will automatically detect if it is an inverted barcode or not.
