### ISSUE TITLE
Crash when viewing certain entries in history

### ISSUE THREAD

**Issue by ghse23** [Fr4gorSoftware/SecScanQR#31]
When scanning [this Data Matrix Code](https://github.com/zxing/zxing/issues/365), and subsequently viewing its entry in the history tab, the application crashes.

**Comment by Fr4gorSoftware** [comment]
I will check if this problem exists for all data matrix codes or only for this specific one.

**Comment by Fr4gorSoftware** [comment]
Fix is now implemented and will be in the next version of SecScanQR
