### ISSUE TITLE
custom URL and fetch a lookup page?

### ISSUE THREAD

**Issue by govvin** [Fr4gorSoftware/SecScanQR#33]
This looks like a promising alternative to what we already have in the Fdroid repos. Kudos.

Apart from custom URL as mentioned in ticket #26 , how about the ability to display a page without leaving the app, after loading a custom URL?

This is useful for specific lookup results. It might say for example, that the barcode is not in the database, or that barcode is in the database, and will display additional information.

**Comment by Fr4gorSoftware** [comment]
Then the app would need an extra permission like android.permission.INTERNET. This would contradict with the goal of keeping permissions as low as possible
