### ISSUE TITLE
allow import of VCard from file

### ISSUE THREAD

**Issue by dadosch** [Fr4gorSoftware/SecScanQR#39]
A vcard file would be useful because you wouldn't need to type in the text manually

**Comment by Fr4gorSoftware** [comment]
Added to the list of upcoming features: https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features

**Comment by Woi** [comment]
+1

**Comment by Fr4gorSoftware** [comment]
Vcards can be imported via the Contacts app with version 1.2.5
