### ISSUE TITLE
Feature Request: Helper for Code Generation

### ISSUE THREAD

**Issue by andunix** [Fr4gorSoftware/SecScanQR#4]
It would be nice, if the code generation could not only convert text to a qr-code but also has little forms for the different qr-codes (text, url, email, phone, sms, geo location, vcard, event, wifi config).

**Comment by Fr4gorSoftware** [comment]
Please take a look at the attached picture. Is that what you mean? In the background, the App would create a validate vCard for example and then create a QR-Code out of it.
![scratch - different helpers](https://user-images.githubusercontent.com/30445568/30923083-40b08cfe-a3ab-11e7-8143-bd7c5099828b.png)

**Comment by andunix** [comment]
Yes, this is exactly what I was thinking about. 👍

**Comment by spaetz** [comment]
Picture looks good, I was about to propose the same. Other types I would like to see are: links, wifi autologin codes.

**Comment by Fr4gorSoftware** [comment]
I like the feature idea. It could take a while until I have the time to implement this feature. I let this issue open so you can request specific helpers during the development process

**Comment by Fr4gorSoftware** [comment]
First helpers are implemented in version 1.1.2. Coming soon to the f-droid store

**Comment by andunix** [comment]
Version 1.1.2 didn't make it to F-Droid, the error is: "cannot find symbol R.id.txtqrcode".
Can you please have a look?

**Comment by Fr4gorSoftware** [comment]
I pushed a hotfix. Thanks for letting me know that the build wasn't successful

**Comment by Fr4gorSoftware** [comment]
I used a not valid gradle version for F-Droid (Build failed again 😞) I will push a Hotfix this weekend (hopefully the last for this version)
