### ISSUE TITLE
Set as default for dealing with scan intents

### ISSUE THREAD

**Issue by hyiltiz** [Fr4gorSoftware/SecScanQR#41]
I have both Barcode Scanner from ZXing and SecScanQR (1.1.6 Build 9) installed (from F-Droid). When an external app tries to scan a QR code (e.g. from within Fennec F-Droid browser address bar QR code button or Sleep with Android scan QR code feature), the Barcode Scanner from ZXing starts automatically, without asking which app to choose. I installed another barcode scanner from F-Droid, and tried scanning from an external app. Now, LineageOS asks which app to use, and lists Barcode Scanner and the new one I installed, but not SecScanQR. There is no option in system Settings set for default for neither Barcode Scanner or SecScanQR. If I uninstall Barcode Scanner from ZXing, then system just thinks there is no barcode scanner installed.

Is there any way I can start/call/open SecScanQR from external app as a default code scanner?

**Comment by Fr4gorSoftware** [comment]
Hi,
would be a good idea and I also looked up what kind of intent filter they use to call the scanner but I didn't managed to get a working solution. Maybe there is someone in the community to help me developing this part of code.

**Comment by haarp** [comment]
It seems SecScanQR doesn't provide an intent at all. This explains why the Zxing scanner starts automatically. When I try scanning with only SecSCanQR installed, many apps tell me that they didn't find any QR code scanner.

**Comment by Fr4gorSoftware** [comment]
Good news SecScanQR can be used by third party apps with version 1.2.3  but the apps itself have to add SecScanQR to their whitelist.  Syncthing-android will support SecScanQR with version 1.1.3.
