### ISSUE TITLE
Feature Request: Dark theme

### ISSUE THREAD

**Issue by pyroshroom** [Fr4gorSoftware/SecScanQR#43]
Hi, I would like to request a dark theme option for the app interface

**Comment by Fr4gorSoftware** [comment]
In Version 1.1.7 there will be a dark theme for the scanner. In the next versions I will continue with the Generator and History. You can change the theme in the scanner settings (for now)
![2018_08_19_12_30_58](https://user-images.githubusercontent.com/30445568/44307496-dbf40800-a3a3-11e8-817f-d8ec87034f2f.png)

**Comment by Fr4gorSoftware** [comment]
except the settings everything will have a dark theme with Version 1.2.5
