### ISSUE TITLE
Feature request : possibility to use the front cam

### ISSUE THREAD

**Issue by Maxtille** [Fr4gorSoftware/SecScanQR#47]
Hey there ! 
The back of my phone is in glass and it's broken which means my rear camera is unusable :/ 
It would be amazing to be able to scan codes again by allowing to swap on the other cam ! Or maybe the idea of scanning from an existing picture would be enough ?

**Comment by Fr4gorSoftware** [comment]
Hi,
this is already implemented since version 1.1.7 :-)
