### ISSUE TITLE
Feature idea: "share" action to generate a QR from selected text

### ISSUE THREAD

**Issue by davux** [Fr4gorSoftware/SecScanQR#5]
Title says it all. What do you think?

**Comment by Fr4gorSoftware** [comment]
You mean a share button for the generated QR code?

**Comment by andunix** [comment]
I think he means to register a share action "Generate QR Code" to generate qr codes from other apps.

**Comment by davux** [comment]
@andunix is correct.

**Comment by Fr4gorSoftware** [comment]
Ah ok, now I got it. Good idea, I put that on the list for upcoming features.
https://github.com/Fr4gorSoftware/SecScanQR/wiki/Upcoming-Features
