### ISSUE TITLE
Add feature to change camera orientation

### ISSUE THREAD

**Issue by x2k13** [Fr4gorSoftware/SecScanQR#50]
It would be nice to have a feature to choose the scanner orientation from landscape to portrait and vice versa, because the app in portrait and the scanner in landscape mode is awful.

**Comment by Fr4gorSoftware** [comment]
Added to list for upcoming features

**Comment by haarp** [comment]
I concur. This is one of the best QR scanners I've seen so far, but the sudden orientation switch is kind of rough. Thanks!
