### ISSUE TITLE
AGMC Holding is stealing your app

### ISSUE THREAD

**Issue by DPTJKKVH** [Fr4gorSoftware/SecScanQR#51]
AGMC Holding is offering your app under the name of "WFDP Verification" on the Google Play Store: https://play.google.com/store/apps/details?id=de.t_dankworth.secscanqr

They even use the exact same app name de.t_dankworth.secscanqr as you do.

I noticed this because my alternative Play Store (Yalp Store) tried to download and install an update to version 1.1.8 and fortunately failed due a signature mismatch.

This is a huge deal IMO since nobody knows what kind of malware those guys might have added to the apk.

Can you please confirm that this is an illegitimate copy of your app? I'll gladly assist in reporting them if so.

**Comment by Fr4gorSoftware** [comment]
First off all thank you for reporting this to me. They don't have my permission and also no copyright notice to the original owner of the base application (me) and also not to ZXing. 
Would be great if you would support me to report this app.

**Comment by DPTJKKVH** [comment]
You should notify ZXing of their copyright being violated. They'll want to take (maybe even legal) action against AGMC Holding themselves for sure.


As the developer a and copyright owner of the app you should use this form: https://support.google.com/legal/contact/lr_dmca?product=googleplay&uraw=&hl=en

This is the Guide for you as the owner: https://support.google.com/legal/troubleshooter/1114905#ts=1115643%2C1115789%2C1117010%2C1697925


As a third party I'm not allowed to file an official complaint to Google but I'll report it as being obviously stolen via the normal contact form.

This is a very obvious case since they were too lazy or stupid to even change the app name. So don't be shy to file the copyright complaint. The worst that could happen is that Google will not accept it which I highly doubt since it's that obvious.

**Comment by DPTJKKVH** [comment]
Ich sehe gerade, du kommst aus Deutschland. Also der Prozess ist an sich recht simpel. Du musst halt Google erklären wo die App dein Copyright verletzt, was hier derart offensichtlich ist, dass das kein Problem darstellen sollte.

Ab dann liegt die Sache bei Google und die entscheiden darüber.

Auch wenn es so wirkt, aber du stößt damit noch kein Gerichtsverfahren oder sonst etwas an. Das könntest du natürlich auch, aber eben weil darauf nicht einmal die großen Firmen Lust haben, gibt es diese Takedown Notices, bei denen dann Google selbst entscheidet, ohne dass ein riesen Fass auf gemacht werden muss.

Ist zwar alles ein wenig kontraintuitiv für uns OpenSource Freunde, aber es geht halt nicht an, dass kommerzielle Akteure sich an freier Software bedienen ohne Copyright Hinweis und (sofern erforderlich) nach Erlaubnis zu fragen. Zumal die deine App echt einfach in weiten Teilen 1:1 kopiert haben.

**Comment by DPTJKKVH** [comment]
Sehr gut! :+1:

Verdient hätte es die AGMC Holding, weil ich wette auch deren anderen Apps sind geklaut. Aber du hast Recht: Für dich als Studenten ohne Rechtsschutzversicherung, wären allein die Prozesskosten eine viel zu große Last. Und du willst ja kein Kapital daraus schlagen, sondern einfach dass deine Arbeit und die Open Source Lizenzen respektiert werden. Darum habe ich gar nicht weiter in diese Richtung erklärt.

Ich kann verstehen, wenn du nicht auf dem PlayStore veröffentlichen willst oder wolltest. Schließlich ist das kein freier Marktplatz, wie z.B. F-Droid. Ich bin mir nicht sicher, aber es könnte sogar sein, dass es zumindest einmal Geld kostet, um einen offiziellen Developer Account zu bekommen. Das müsstest du dann nachschauen, falls du nicht bereits einen Dev-Account hast.

Ansonsten gebe ich dir jedoch Recht: Wenn du mit deiner eigenen App im PlayStore den Namen de.t_dankworth.secscanqr blockierst, kann zumindest niemand mehr derart dreist klauen, dass unbedarfte Nutzer auf einmal die falsche App als Update angeboten bekommen.

Ich will da keinen sozialen Druck auf dich ausüben. Das ist deine Zeit und ggf. Geld und das sollst deshalb auch nur du entscheiden.

Wo wir bei Geld sind. Ich werde dir im Laufe dieses oder des nächsten Tages eine kleine Spende da lassen. Deine App ist echt nice, da sie viel weniger Rechte braucht und du hast die Courage für dich und die OpenSource Community einzustehen. Das ist gut und richtig und sollte belohnt werden. Danke, dass du ein aktiver Teil der OpenSource Community bist!

**Comment by Fr4gorSoftware** [comment]
> Verdient hätte es die AGMC Holding, weil ich wette auch deren anderen Apps sind geklaut.

Davon kann man ausgehen, jedoch fehlen mir da Beweise bzw. die echten App Inhaber

> Ich kann verstehen, wenn du nicht auf dem PlayStore veröffentlichen willst oder wolltest.

Durch dieses Ereignis wird sich dieses wahrscheinlich ändern, aber ich muss mich noch mal schlaumachen, was den Dev-Account angeht.

> Ich will da keinen sozialen Druck auf dich ausüben. Das ist deine Zeit und ggf. Geld und das sollst deshalb auch nur du entscheiden.

Ach quatsch alles gut ;-)

> Ich sehe gerade du hast nur PayPal und mit denen liege ich leider gerade über Kreuz... Dann lass dir zumindest noch einmal ein aufrichtiges Danke von mir sagen!

Das kann ich gut verstehen und das macht ja auch OpenSource aus, jeder trägt das bei was er/sie kann oder will und Du hast mir schon geholfen, indem Du mir diesen Fall gemeldet hast. Außerdem danke für Dein Lob :-)

**Comment by DPTJKKVH** [comment]
Schreibe dann bitte hier, sobald sich Google gemeldet hat. Ich hoffe du kannst den Fall dann erfolgreich abschließen und musst kein "wontfix" draus machen. :wink:

**Comment by Fr4gorSoftware** [comment]
Gerade kam eine Antwort von Google:

> Sehr geehrte Damen und Herren,
vielen Dank für Ihre Anfrage.
Geben Sie für jede der folgenden URLs genau die Inhalte an, die Ihrer Meinung nach Ihr Urheberrecht verletzen:
https://play.google.com/store/apps/details?id=de.t_dankworth.secscanqr
Bitte senden Sie uns außerdem ein Bild oder einen Screenshot der mutmaßlich rechtsverletzenden Inhalte aus der betreffenden App.
Ohne diese Angaben können wir Ihren Antrag nicht bearbeiten.
Falls Sie Bedenken haben, eine kostenpflichtige App herunterzuladen, finden Sie unter https://support.google.com/googleplay/answer/134336 Informationen zu den Erstattungsrichtlinien für Google Play-Apps.
Mit freundlichen Grüßen
Ihr Google-Team 

Ich habe den nun noch mal erklärt, weswegen diese App gegen die Richtlinien verstößt, mal schauen...

**Comment by DPTJKKVH** [comment]
Oh man ey. Ich hasse es, wenn man nur so vorgefertigte Textbausteine bekommt. Da hat der Bot oder Support-Sklave vollkommen verpeilt um was es geht.

Hoffentlich klappt es im zweiten Anlauf. Kann ja nicht sein, dass der Google-Support nicht die eigene FAQ gelesen hat.

**Comment by Fr4gorSoftware** [comment]
Endgültiges Urteil von Google:
> Sehr geehrte Damen und Herren,
vielen Dank für Ihre Anfrage.
Google wird derzeit keine Maßnahmen ergreifen. Wir empfehlen Ihnen, strittige Fragen direkt mit der Person zu klären, die den Inhalt gepostet hat...

**Comment by DPTJKKVH** [comment]
Ich kann es nicht fassen. Wenn du ein Unternehmen mit DMCA-Schnittstelle wärst, dann würde der Inhalt erst einmal ohne Prüfung offline genommen werden, um dann im Nachhinein zu klären, ob es vll doch kein Verstoß war. Als normaler Entwickler darfst du froh sein, wenn Google dir noch sagt, dass du ihnen vollkommen egal bist.

Ohne Anwalt, der die eine Abmahnung und Unterlassungserklärung anfertigt, kommst du jetzt leider nicht weiter. (Ich weiß, das kommt nicht in Frage.)

Es tut mir leid, dass das System so unfair ist und du nun Arbeit für nichts hattest. 

Was du noch machen könntest, ist die Version auf 1.1.9 oder höher zu heben, damit der Fake im PlayStore nicht als neuere Version "erkannt" wird.

**Comment by Fr4gorSoftware** [comment]
> Was du noch machen könntest, ist die Version auf 1.1.9 oder höher zu heben, damit der Fake im PlayStore nicht als neuere Version "erkannt" wird.

Ich glaube, dann würde AGMC einfach eine weitere Versionsnummer drauflegen. Ich sehe darin also wenig Erfolg.

Ich bin am Überlegen die Entwickler einfach anzuschreiben, sollte das nichts bringen, gehe ich noch mal zu Google und zitiere denen die GPL vor, damit auch Google die Rechtsverletzung erkennen sollte.

**Comment by IzzySoft** [comment]
Für mich sieht es so aus, asl ob AGMC "eingepackt hat" – da gab es schon seit Monaten keine Updates mehr. Eine App wurde bereits "depublished", weder website noch Mailserver sind mehr erreichbar (Domain löst nicht mehr auf).

Wie ich im verlinkten Issue schrieb, halte ich das Ganze auch eher für Schussligkeit. Habe die App nicht selbst installiert (nutze kein Playstore mehr), aber es schaut danach aus als hätten sie auf dem SecScanQR Code aufgebaut (kleiner Anbau) und vergessen, die Package ID zu ändern (anstatt eine eigene App zu bauen, und SecScanQR als "Bibliothek" einzubinden).

Eventuell lohnt sich ein zweiter Anlauf bei "big G" – mit dem Hinweis darauf, dass die Firma mittlerweile "verschwunden" ist. Eventuell hat sie auch nur "umfirmiert" in eine Ltd: https://agmcltd.com/products/websites (oder der Firmenname bei GPlay war auch nicht echt)…

**Comment by Fr4gorSoftware** [comment]
Ich bin mittlerweile auch schon seit  einem Monat wieder in Runde 2 mit Google, weil mir aufgefallen ist, dass deren Domain frei zum Verkauf steht. Mal schauen, was daraus wird...

**Comment by IzzySoft** [comment]
Wenn Geld keine Rolle spielt: kaufen, und dann per Mail mit Absender von dort die Löschung der App(s) beantragen (Begründung: Zugangsdaten/Wallet/Keystore bei Hardware-Crash verloren) :rofl:

Ernsthaft: Viel Erfolg!

**Comment by Fr4gorSoftware** [comment]
Eben kam eine erfreuliche Nachricht von Google:

> Hello,
Thanks for reaching out to us.
In accordance with the Digital Millennium Copyright Act, we have completed processing your infringement notice. We are in the process of disabling access to the content in question at the following URL(s):
https://play.google.com/store/apps/details?id=de.t_dankworth.secscanqr
The content will be removed shortly.

**Comment by IzzySoft** [comment]
Great, thanks for letting us know!

**Comment by DPTJKKVH** [comment]
Hey @Fr4gorSoftware , das sind wirklich großartige Neuigkeiten! Freie Lizenzen haben gefälligst genauso respektiert zu werden, wie alle anderen auch.

Ich frag mich, warum Google nicht beim ersten Mal bereits so reagiert hat. Hast du diesmal etwas anders gemacht?

**Comment by Fr4gorSoftware** [comment]
> Hast du diesmal etwas anders gemacht?

Außer den Verstoß gegen die GPL Lizenz noch deutlicher zu machen, eigentlich nicht :rofl:
