### ISSUE TITLE
auto-copy to clipboard

### ISSUE THREAD

**Issue by katrinleinweber** [Fr4gorSoftware/SecScanQR#6]
Hello! Thanks for providing an alternative to the aged [Barcode Scanner](https://f-droid.org/packages/com.google.zxing.client.android/) :-)   I'm not sure whether you tried that app, but for me, parting from it is hard for two reasons:

1) it automatically copies QR content to the clipboard, maybe because it assumes that for most downstream uses, this will help. Have you considered adding this as well? Do you see any risks making this a default?
2) see #7

**Comment by Fr4gorSoftware** [comment]
I see no risks adding this. I wouldn't enable it as default but as an option in the settings like I explained it in the issue #7. This feature is planned for the next version.

**Comment by trymeouteh** [comment]
This would be nice. But This should be a setting to turn this on and off.
