### ISSUE TITLE
[Feature Request] New Search Provider Startpage

### ISSUE THREAD

**Issue by SabrinaFinkel** [Fr4gorSoftware/SecScanQR#60]
What do you think of adding [Startpage](https://www.startpage.com/en/advanced-search.html?&t=default) as search provider?

**Comment by malnvenshorn** [comment]
Instead of adding a new search provider I'd suggest to make it possible to add/delete them manually.

**Comment by Fr4gorSoftware** [comment]
@SabrinaFinkel Planned for next release 
@malnvenshorn Right now I don't think this would be worth investing time in because the most people use one of the popular once.

**Comment by peegtaar** [comment]
Awesome feature, i really love Startpage because i did some and there the only one with real privacy, DuckDuckGo did keep somewhere some data.

**Comment by Fr4gorSoftware** [comment]
Startpage is now implemented and will be available with Version 1.2.0 in a few days in the F-Droid store
