### ISSUE TITLE
[Request] Read/write VCards, connect to Wifi

### ISSUE THREAD

**Issue by malnvenshorn** [Fr4gorSoftware/SecScanQR#62]
At the moment this app does only one thing, reading QR codes. But unless you scanned a link you cannot do much with the result. E.g. after you scanned a VCard you still have to add the contact manually and if you scanned login details to a WIFI network you cannot simply connect to it. The same when you want to create QR codes, you have to add all information manually (e.g. this app doesn't show up in the share menu of contacts).

Are those features planned or is the philosophy of this app to use as less permissions as possible and to renounce such convenience features?

**Comment by Fr4gorSoftware** [comment]
This feature would need further permissions which would be against the philosophy: Privacy first, features second ;-)

**Comment by aha999** [comment]
Then, it could ask for permissions when you use the feature.
