### ISSUE TITLE
[Feature Request] Flashlight Button

### ISSUE THREAD

**Issue by trymeouteh** [Fr4gorSoftware/SecScanQR#65]
For some reason my volume buttons are not working on my Samsung Galaxy S6 for turning on the flashlight in the camera mode. But I would perfer a flashlight button in the top-right corner you can tap to turn the flashlight on/off.

BTW: Great App! I been searching a long time for a free, open source, F-Driod QR & barcode scanner and generator app. Thank you so much for this app!

**Comment by Fr4gorSoftware** [comment]
major changes to specific parts of the app would be needed which is not planned at the moment. To activate the flashlight "volume up" should work if the volume keys work at all
