### ISSUE TITLE
Download error when downloading via F-Droid app

### ISSUE THREAD

**Issue by bunchofsage** [Fr4gorSoftware/SecScanQR#69]
Tried downloading your app today in F-Droid app with the big INSTALL button. It seems an older version (9) is tried and not available anymore.

This prevents downloading and installing SecScanQR over F-Droid app. So I ended up downloading the latest version [(12)](https://f-droid.org/repo/de.t_dankworth.secscanqr_12.apk) from https://f-droid.org/en/packages/de.t_dankworth.secscanqr/

![screenshot_20181225-105747](https://user-images.githubusercontent.com/23432291/50420495-3829d580-0837-11e9-894d-8ce61ceff5a4.jpg)

**Comment by Fr4gorSoftware** [comment]
This is because you have to update the packages from F-Droid. You can do that by wipe down on the main screen of the store. This should update the packages then you should see the last update was 1 month ago and not 7 months ago
