### ISSUE TITLE
add option to start scanning automatically

### ISSUE THREAD

**Issue by katrinleinweber** [Fr4gorSoftware/SecScanQR#7]
related to #6

Having almost exclusively the use-case of scanning, rather than generating QRs, I grew fond of [Barcode Scanner](https://github.com/zxing/zxing)'s behavior of auto-starting the camera seeker. How about adding this as an option here?

**Comment by Fr4gorSoftware** [comment]
Good idea. In the next version, there will be settings and over the settings, you can choose the scanner as autostart.
