### ISSUE TITLE
Add option to prevent screenshots

### ISSUE THREAD

**Issue by ghost** [Fr4gorSoftware/SecScanQR#70]
First off, I would like to say thank you for making this great barcode scanning app! I have stopped using ZXing in favour of this open source alternative available on F-Droid.

One of the things I use QR codes for is transferring passwords from my desktop PC to Android. This requires me to put a lot of trust into an Android barcode scanning app... and Android itself.

Android is constantly taking screenshots of everything. These screenshots are saved to storage in PNG format for some reason. These screenshots are used for the recents screen to display a cached image of the app. Once the cached image is no longer used it is deleted but not overwritten, therefore ANY APP can scan the free space to recover the images.

You can use `FLAG_SECURE` to prevent this (it disables screenshots).

> Window flag: treat the content of the window as secure, preventing it from appearing in screenshots or from being viewed on non-secure displays. 

https://developer.android.com/reference/android/view/Display#FLAG_SECURE

What most app developers do is add a toggle option called "Screen security".

**Comment by Fr4gorSoftware** [comment]
I didn't knew that Android takes screenshots automatically...
Because security is the highest priority for this app the requested feature will be added to SecScanQR in the next version. 
It will be activated by deafult and I add an option to deactivate it manuelly

**Comment by Fr4gorSoftware** [comment]
Implemented and ready for release 1.2.0
except for the scanning activity where it is not possible at the moment

**Comment by agent0404** [comment]
Unfortunately the place where it matters most is during the scanning activity. Why is it not possible to block screenshots while scanning?

https://news.ycombinator.com/item?id=18419959
https://tech.michaelaltfield.net/2018/11/09/android-security-auditing-investigating-unauthorized-screenshots/

**Comment by Fr4gorSoftware** [comment]
Because SecScanQR uses the IntentIntegrator from ZXing to scan QR-Codes and this does not support that functionality. I have to check if there is an other way to prevent this
