### ISSUE TITLE
Bitcoin donate

### ISSUE THREAD

**Issue by peegtaar** [Fr4gorSoftware/SecScanQR#71]
Hi i love your app but can u make it possible to donate with Bitcoin?, i don't like to donate with Paypal and i avoid the bigger companies.

**Comment by Fr4gorSoftware** [comment]
Thank you for the kind words. I have no experience with bitcoin but I will do some research and then I will create a wallet because you are not the first one who asks if I have a bitcoin wallet. I will give you an update when I successfully created a wallet ;-)

**Comment by Fr4gorSoftware** [comment]
Bitcoin address is now available in the README file of the project
