### ISSUE TITLE
Feature request: Decode codes from an image

### ISSUE THREAD

**Issue by vanhamiel** [Fr4gorSoftware/SecScanQR#76]
Hi, thanks a lot for your app. It's fast, clean and simply to use, a must have.
The qr reader i used to use had a nice feature to read qr/barcodes from an image (simply share the file to the app), i think it would be a great addiction to your work.
Sorry for my english and thanks for your attention :)

**Comment by graphixillusion** [comment]
Hi there! I would like to suggest the same thing! Would be awesome!

**Comment by Fr4gorSoftware** [comment]
I will check that and if it is possible I will add this feature

**Comment by Fr4gorSoftware** [comment]
feature is implemented and will be available with version 1.2.1
