### ISSUE TITLE
generated QR code is stored with wrong extension .jpg

### ISSUE THREAD

**Issue by ke352802081770314** [Fr4gorSoftware/SecScanQR#78]
when generating a QR code and saving it, I got the filename Mon\ Feb\ 04\ 06:56:23\ GMT+01:00\ 2019.jpg but it turns out that the file is in fact PNG (which makes more sense). The extension should match the content. (Version installed: 1.2.0 Build 13)
By the way, many thanks for this useful app!

**Comment by Fr4gorSoftware** [comment]
Hi, thank you for reporting this bug. I will fix that with the next version
