### ISSUE TITLE
Can't input negative lat/long in geo

### ISSUE THREAD

**Issue by rexy712** [Fr4gorSoftware/SecScanQR#80]
Trying to input a negative longitude and I wasn't allowed to input the minus sign. The example text for longitude contains a negative sign, so I assume it should be allowed

**Comment by Fr4gorSoftware** [comment]
The hint is wrong. You set the negative longitude when the checkbox for east is not checked. The same for latitude but with the checkbox north. 
I will change the hint to prevent misunderstanding
