### ISSUE TITLE
Looking my version that app/fix copyright/look description

### ISSUE THREAD

**Issue by danieldhop** [Fr4gorSoftware/SecScanQR#84]
https://play.google.com/store/apps/details?id=com.ultron.openqrcode

**Comment by Fr4gorSoftware** [comment]
What is different to the original app and where do you show the source code to the public as the GPLv3 license wants it to?
Also I don't see any reference to the original project in the app and in google play

**Comment by UsrPwndUX** [comment]
I came here to make a feature request, scan a barcode image on the phone, and saw this. He states on play store "After all, we've added a new feature that is that you can scan an image by uploading the gallery." That is exactly the feature I was going to request. Unsurprisingly, his app does not have that functionality to scan a barcode from an image in the gallery. It is simply a rebadge of your app.

**Comment by Fr4gorSoftware** [comment]
> I came here to make a feature request, scan a barcode image on the phone

Is already implemented in the current dev version and will be available with Version 1.2.1 #76 

@UsrPwndUX I totally agree with you
@danieldhop I give you another two days to address the issues I mentioned. After that I will get in contact with Google to remove your app from the play store.

**Comment by UsrPwndUX** [comment]
I can't wait for it to hit f-droid. I did some brief looking on Google Play help to see how to report an app that was in violation of a GPL licence, didn't find anything on initial glance.

**Comment by caarmen** [comment]
<img width="503" alt="step1" src="https://user-images.githubusercontent.com/1731388/55062652-b1bfa280-5076-11e9-80d1-9ad02c0fe44e.png">
<img width="797" alt="step2" src="https://user-images.githubusercontent.com/1731388/55062655-b2583900-5076-11e9-9f57-756482696417.png">
<img width="797" alt="step3" src="https://user-images.githubusercontent.com/1731388/55062654-b1bfa280-5076-11e9-8ca0-b7e7ee6fc68c.png">

<img width="797" alt="step4" src="https://user-images.githubusercontent.com/1731388/55062653-b1bfa280-5076-11e9-8a98-51eb1b4fddfb.png">

**Comment by Fr4gorSoftware** [comment]
@danieldhop  I can see that you edited the description for the Google Play Store but you also have to give credit in the app itself for the original project, to the translators of the translations you use and that your app is an GPLv3 app. 
A big thing that is missing is the url to the source code of your version (Missing in the app itself and in the Google Play Store description). At the moment your source code is not open to the public which is a violation to the GPLv3 license.

**Comment by Fr4gorSoftware** [comment]
Answer from Google:

> Hello,
Thanks for reaching out to us.
In accordance with the Digital Millennium Copyright Act, we have completed processing your infringement notice. We are in the process of disabling access to the content in question at the following URL(s):
https://play.google.com/store/apps/details?id=com.ultron.openqrcode
