### ISSUE TITLE
Clone in Play Store using even your package ID

### ISSUE THREAD

**Issue by IzzySoft** [Fr4gorSoftware/SecScanQR#85]
Just to inform you there's an app on Play Store using your code and even your package name, going by the name [WFDP Verification](https://play.google.com/store/apps/details?id=de.t_dankworth.secscanqr) – which at least is confusing. The web address they specify doesn't resolve ("server not found"), same for their mail domain.

I don't think they're doing anything bad with it (maybe just forgot to replace the package name) – the app is free and has no ad or analytics frameworks added. But with your code being protected by the GPL, their app needs to use GPL as well and publish the source, which I cannot see anywhere. Nor did I find the attribution required by term 7b of GPLv3.

**Comment by Fr4gorSoftware** [comment]
Thank you for the report but this app was already mentioned by an other user #51

**Comment by IzzySoft** [comment]
Ah, missed that – apologies!

**Comment by Fr4gorSoftware** [comment]
no problem ;-)
