### ISSUE TITLE
Can't open v 1.2.1

### ISSUE THREAD

**Issue by frauhottelmann** [Fr4gorSoftware/SecScanQR#88]
I downloaded v1.2.1 from F-Droid and the app icon disappeared from the launcher. F-Droid also doesn't show the open button. I downgraded to v1.2.

Phone: BQ Aquaris X2 Pro
OS: Android 9

**Comment by nobodyspecial** [comment]
I have the same issue.

**Comment by Fr4gorSoftware** [comment]
I can confirm this issue. I did a slight mistake in the implementation of the picture scanner which causes this problem. I will release a hotfix today which will be available in some days in the F-Droid store.
