### ISSUE TITLE
Icon disappeared after update

### ISSUE THREAD

**Issue by t-aus-m** [Fr4gorSoftware/SecScanQR#90]
So I just installed the latest update of the app via F-Droid and... yeah... the icon disappeared. So its now impossible to launch the app.

Screenshot for clarification attached. You can see, that the button thats normally there to launch an app, is in fact missing. 

![](https://i.imgur.com/Xq7ugNi.png)

**Comment by Fr4gorSoftware** [comment]
Already mentioned in #88 
Hotfix is already deployed and will be available in the F-Droid store the next days (Version 1.2.2)
