### ISSUE TITLE
Include SQRC in sec Scan QR

### ISSUE THREAD

**Issue by peerzadaaabid** [Fr4gorSoftware/SecScanQR#91]
Hi 
In order to make the QR codes more secure and restrict their information to limited or chosen person, I want to include SQRC in the sec scan QR.
THANKS

**Comment by Fr4gorSoftware** [comment]
Hi, I didn't found any information about QRRC. Can you give me more details?

**Comment by peerzadaaabid** [comment]
I updated the suggestion,  there was a typing mistake
