### ISSUE TITLE
send image to SecScanQR

### ISSUE THREAD

**Issue by hackerb9** [Fr4gorSoftware/SecScanQR#92]
I understand that, for privacy reasons, SSQR may not want permission to read the SD card. However, I do have photos I've taken with other apps that have bar codes in them. It would be nice if SSQR would advertise itself as accepting images so that when I click on the "share" button in my gallery app, SecScanQR will be on the list.

Thanks for the great app!

**Comment by Fr4gorSoftware** [comment]
Hi, 
do you already use the newest version of SecScanQR? There it should be possible to send/share the picture(when you opened it with for example the gallery app) to SecScanQR without the permission to read the SD card

**Comment by hackerb9** [comment]
I have the latest available on F-droid, 1.1.9. When I try to share photos, I'm not seeing SecScanQR in the list.

**Comment by Fr4gorSoftware** [comment]
This is because you have to update the packages from F-Droid. You can do that by wipe down on the main screen of the store. This should update the packages then you should see the latest version of SecScanQR which is 1.2.2

**Comment by hackerb9** [comment]
Thanks. I'm updated to 1.2.2 now and it almost works. When I share an image from my gallery app to SecScanQR it launches the app but doesn't actually open the image. It just says, "Press on the Scan Button to scan a QR-Code/Barcode". I tried two different gallery apps. Restarting the phone did not help.

**Comment by Fr4gorSoftware** [comment]
Then the library which is used for that can't find the qr-code in the picture. This feature will only work properly when nothing else then the qr-code is in the picture. For example you download a qr-code from a website and then try to share it to SecScanQR

**Comment by hackerb9** [comment]
Oh. That behavior makes it seem like no image was processed. 

Should I open a new issue to request that the image be shown and allow it to be moved using the usual interface: one finger moves, two fingers zoom and rotate?

**Comment by Fr4gorSoftware** [comment]
editing of the picture should not be done in SecScanQR itself

**Comment by hackerb9** [comment]
Oh, I don't mean editing. I mean so that SecScanQR will find the bar code.

**Comment by Fr4gorSoftware** [comment]
At the moment I would say that it would not be a good idea to implement that into SecScanQR. Probably every gallery app can do this better then I could implement it. 

I am sorry.

**Comment by hackerb9** [comment]
It's a little bit cumbersome to open an image in SecScanQR, find out it doesn't work, switch to a picture editor, take a guess at what SecScanQR wants, save the image, resend the photo to SecScanQR, find out it still doesn't work, switch back to the picture editor, tweak it some more, send it to SecScanQR.... 

As you can imagine, it would save time if SecScanQR was able to watch the tweaks happening and find barcodes immediately, just as it does for video. 

If you are unable to implement it now, please leave this bug open, marked as Wishlist and/or Help Wanted. Perhaps somebody knows how to do this.

I bet there is already a Free Software widget for basic image manipulation. Maybe there is a way for it to appear like a video source, which SecScanQR knows how to use.

**Comment by Fr4gorSoftware** [comment]
I understand your point. I would prefer opening a new issue because it is a new feature. Possible structure:
```
## Feature description

### Use cases

## Benefits

For whom and why.

## Requirements

## Links / references

```

**Comment by Iey4iej3** [comment]
I don't understand how to proceed when the QR code is only part of an image. I tried to crop out the QR code from a screenshot but SecScanQR still failed to read out the result. I am also very confused by the fact that the algorithm could identify the QR code from camera while unable to analyze a very regular screenshot.
