### ISSUE TITLE
Addition of SQRC

### ISSUE THREAD

**Issue by peerzadaaabid** [Fr4gorSoftware/SecScanQR#93]
Hi

You know privacy is the most endorsed and preferred thing these days. So the idea which I want to include is

● Addition of SQRC that has data reading restriction.

lock-padlock-security-secure-locked-barcode-qr_code-512.png

Proposal description
In proposal description I will mentioned why and how I want to modify the secScanaQR.

Development of SQRC will let the company to manage the private information and a company’s vital information.

The infromation in an SQRC consists of public and private sections. A single code can carry thse two types of information in a sophisticated manner.The SQRC code looks like the simple QR code but its coded data which can be scanned by specified scanners is an amazing thing which is needed to implement here.

Moreover, it will let the users to code information of any type.

THANKS

**Comment by Fr4gorSoftware** [comment]
Hi,

I have some questions regarding SQRC:

- SQRC is a trademark of Denso Wave -> Is it even possible and legal to implement SQRC in an Open Source app
- I don't find any API for SQRC. How do you wanna implement it. 
- I can't open lock-padlock-security-secure-locked-barcode-qr_code-512.png. Could you please check that.
- What do you say to the [criticism to SQRC from the creator of ZXing ](https://groups.google.com/forum/#!topic/zxing/8w_0Dr15i2E)

**Comment by Fr4gorSoftware** [comment]
closed because of inactivity
