### ISSUE TITLE
Send VCard to addressbook

### ISSUE THREAD

**Issue by IzzySoft** [Fr4gorSoftware/SecScanQR#94]
When scanning a QR code resolving to a contact (e.g. in VCF), I miss a way to add that contact(s) to my address book. I'm not an Android dev, but IIRC the contacts app provides an intent for that, to hand over the (decoded) VCF.

So with a contact detected, could there be an option to "add to addressbook" – like there is to open an URL with the browser? Just handing the data over to an intent wouldn't need any extra permissions (like `WRITE_CONTACTS`), as access to contacts then would be handled by the contacts app itself.

**Comment by Fr4gorSoftware** [comment]
I will take a look at that and if it is possible without any extra permissions I will implement it.
Can you provide me a link to IIRC? I didn't found it in the F-Droid and Play Store.

**Comment by IzzySoft** [comment]
Ooops? Sure, [here's the link to IIRC](https://www.urbandictionary.com/define.php?term=iirc) :rofl: It's an acronym that stands for "If I Remember Correctly". Sorry if that caused confusion – it's used that often in "tech discussions", one thinks it's already normal language.

Thanks for looking into it! And AFAIK (As Far As I Know), it won't need any extra permission. Like handing a phone number to the caller app does not (so I don't understand why so many apps request CALL_PHONE – just so they can also hit the green "call" button?).

**Comment by Fr4gorSoftware** [comment]
ah ok that explains a lot. This acronym was new to me   :laughing:

**Comment by IzzySoft** [comment]
IMHO and AFAIR there are several more. Some I also tend to forget frequently (like IANAL for "I Am Not A Lawyer"). Urban dictionary is often quite helpful then.

Well, OK: `</OT>` *[ROFLMAO](https://www.urbandictionary.com/define.php?term=ROFLMAO)*

OMG, just now I understand that supid "chicken crossing the road" joke! I'm not a native English speaker, so all those 30+ years since hearing it the first time, I didn't get the double meaning of "it wanted to get to [the other side](https://www.urbandictionary.com/define.php?term=The%20Other%20Side)…

**Comment by Woi** [comment]
+1

**Comment by ikarus23** [comment]
+1

Also, I would love to share contacts via QR codes. I don't think you need an extra permission as long as the workflow is: open contacts app, select contact, use share button, select this lovely app and it will create a vcard QR code.

Should I open another issue with this request? Because it is not sending but receiving addressbook data (and generating a QR code from it).

**Comment by IzzySoft** [comment]
@Fr4gorSoftware will this one make it to the list of planned features? I always recommend your app in my courses and get asked for that…

**Comment by Fr4gorSoftware** [comment]
I was quite busy the last months because of my bachelor theses but now I have some more time. I will look into this as fast as possible

**Comment by Fr4gorSoftware** [comment]
@ikarus23 would be better if you create a new issue for that

**Comment by ikarus23** [comment]
@Fr4gorSoftware Sure! Done. ;)

**Comment by Fr4gorSoftware** [comment]
Feature is implemented with version 1.2.4. Tested with VCARD Version 2.1

**Comment by IzzySoft** [comment]
Thanks a lot! That makes for another promo session in a week, and in two weeks (in two of my courses I give for Android users). I already recommended your app there in the past – but now you gave me another heavy argument to *strongly* recommend it :smile:

Looking forward to the feature @ikarus23 suggested, which would make this a two-way solution and complete the "contact exchange process".

**Comment by Fr4gorSoftware** [comment]
Thank you for the promo and support :-)
With the next version the issue of @ikarus23 will be addressed ;-)

**Comment by IzzySoft** [comment]
Great! I'll include that hint in my next promos :smiley:
