### ISSUE TITLE
Show scan history in descending order

### ISSUE THREAD

**Issue by bunchofsage** [Fr4gorSoftware/SecScanQR#99]
I think it's more helpful to see your most recent scan entries first.

Imagine you just scanned 5 items and want to see them again and do something with it. Currently you need to scroll all the way down to access them. A feed-like "sort-by date desc" order would solve that better.

**Comment by Fr4gorSoftware** [comment]
Good idea, planned for next release

**Comment by janitress** [comment]
I second this feature wish by bunchofsage.

**Comment by Fr4gorSoftware** [comment]
history will be ordered by desc with version 1.2.4
